[project]
name = "ortools-vrp-solver"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ortools",
    "fastapi[standard]",
    "httpx",
    "uvicorn",
]

[dependency-groups]
dev = [
    "modal",
]
